main/urls.py
from django.urls import path
from main.views import show_main, create_product, show_xml, show_json, show_xml_by_id, show_json_by_id, register,\
                       login_user, logout_user, inc_product_amount, dec_product_amount, remove_product, get_product_json, add_product_ajax, delete_product_ajax, create_product_flutter
from main.models import Product

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('inc_product_amount/<int:id>', inc_product_amount, name='inc_product_amount'),
    path('dec_product_amount/<int:id>', dec_product_amount, name='dec_product_amount'),
    path('remove_product/<int:id>', remove_product, name='remove_product'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-ajax/', add_product_ajax, name='add_product_ajax'),
    path('delete_product_ajax/<int:id>', delete_product_ajax, name='delete_product_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),

]

warkop_kalisetail/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),

]

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    amount = models.IntegerField()
    price = models.IntegerField()
    description = models.TextField()

    def __str__(self):
        return self.name

main/forms.py
from django.forms import ModelForm
from main.models import Product

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name", "amount", "price", "description"]

main/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from main.forms import ProductForm
from django.urls import reverse
from main.models import Product
from django.http import HttpResponse
from django.core import serializers
from main.models import Product
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
import datetime
import json

# Create your views here.
@login_required(login_url='/login')
def show_main(request):
    products = Product.objects.filter(user=request.user)

    context = {
        'nama': request.user.username,
        'kelas': 'PBP E',
        'products': products,
        'total_products' : products.count(),
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, "main.html", context)

def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_product.html", context)

def show_xml(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def inc_product_amount(request, id):
    product = Product.objects.get(id=id)
    product.amount += 1
    product.save()
    
    response = HttpResponseRedirect(reverse("main:show_main"))
    return response

def dec_product_amount(request, id):
    product = Product.objects.get(id=id)
    if (product.amount > 0):
        product.amount -= 1
        product.save()

    response = HttpResponseRedirect(reverse("main:show_main"))
    return response

def remove_product(request, id):
    Product.objects.filter(pk=id).delete()

    response = HttpResponseRedirect(reverse("main:show_main"))
    return response

def get_product_json(request):
    product_item = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', product_item))

@csrf_exempt
def add_product_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        amount = request.POST.get("amount")
        price = request.POST.get("price")
        description = request.POST.get("description")
        user = request.user

        new_product = Product(name=name,amount=amount, price=price, description=description, user=user)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)
    return HttpResponseNotFound()

@csrf_exempt
def delete_product_ajax(request, id):
    product = Product.objects.get(pk=id)
    product.delete()
    response = HttpResponseRedirect(reverse("main:show_main"))
    return response

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':

        data = json.loads(request.body)

        new_product = Product.objects.create(
            user = request.user,
            name = data["name"],
            amount = data["amount"],
            price = int(data["price"]),
            description = data["description"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}
{% block content %}
<style>
    @import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap');


    body {
        background-color: #FFFDFA;
    }

    .container-login {
        margin-top: 22vh;
        margin-right: 15vw;
        margin-left: 15vw;
        background-color: #ffffff;

        padding-bottom: 3rem;
        padding-top: 3rem;
        padding-right: 3rem;
        padding-left: 3rem;

        box-shadow: 0px 1rem 2rem #EFEFEF;
        border-radius: 16px;

    }

    .login-header {
        padding-bottom: 4rem;
    }

    .warkop-kalisetail {
        font-family: 'Plus Jakarta Sans', sans-serif;
        font-weight: 700;
        text-align: center;
        color: #252B48;
        padding-left: 1rem;
        font-size: 3rem;

        margin-bottom: -0.2rem;
        
    }

    .height-kalisetail{
        font-family: 'Plus Jakarta Sans', sans-serif;
        font-weight: 700;
        text-align: center;
        color: #252B48;
        font-size: 1.5rem;
        color: #DD7339;

    }

    .login-username-input {
        font-family: 'Plus Jakarta Sans', sans-serif;
        font-weight: 600;

        padding-bottom: 1rem;
    }

    .login-password-input {
        font-family: 'Plus Jakarta Sans', sans-serif;
        font-weight: 600;

        padding-bottom: 1rem;
    }

    .login-button{
        display:block;
        width:100%;
        

        margin-top: 1rem;
        margin-bottom: 2rem;
    }

    .register {
        font-family: 'Plus Jakarta Sans', sans-serif;
        font-weight: 400;
        text-align: center;
    }

</style>

<div class="container-login">
    <div class = "login-header">
        <div class="warkop-kalisetail">
            Warkop Kalisetail
        </div>
        <div class="height-kalisetail">
            + 272 M
        </div>
    </div>
        <form method="POST" action="">
            {% csrf_token %}

            <div class="login-username-input">
                Username:
                <input type="text" name="username" placeholder="Username" class="form-control">
            </div>

            <div class="login-password-input">
                Password:
                <input type="password" name="password" placeholder="Password" class="form-control">
            </div>

            {% if messages %}
            <ul>
                {% for message in messages %}
                <li>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}

            <button class="login-button" type="submit" value="Login">
                Login
            </button>
        </form>


        <div class="register">
            Don't have an account yet?
            <a href="{% url 'main:register' %}">Register Now</a>
        </div>

</div>

{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Register</title>
{% endblock meta %}

{% block content %}
<style>
    @import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap');

    body {
        background-color: #FFFDFA;
    }

    .container-register {
        margin-top: 14vh;
        margin-right: 15vw;
        margin-left: 15vw;
        background-color: #ffffff;

        padding-bottom: 3rem;
        padding-top: 3rem;
        padding-right: 3rem;
        padding-left: 3rem;

        box-shadow: 0px 1rem 2rem #EFEFEF;
        border-radius: 16px;
    }


    /* Style form fields and labels */
    .form-group {
        margin-bottom: 2rem;
    }

    label {
        display: block;
        font-weight: bold;
    }


    input[type="text"],
    input[type="password"],
    textarea {
        width: 100%;
        padding: 0.4rem;
        border: 1px solid #ccc;
        border-radius: 5px;
    }

    .errorlist {
        color: red;
    }

    .register-header {
        padding-bottom: 4rem;
    }

    .warkop-kalisetail {
        font-family: 'Plus Jakarta Sans', sans-serif;
        font-weight: 700;
        text-align: center;
        color: #252B48;
        padding-left: 1rem;
        font-size: 3rem;

        margin-bottom: -0.2rem;

    }

    .height-kalisetail{
        font-family: 'Plus Jakarta Sans', sans-serif;
        font-weight: 700;
        text-align: center;
        color: #252B48;
        font-size: 1.5rem;
        color: #DD7339;
    }

    .register-button{
        display:block;
        width:100%;
        margin-top: 1rem;
        margin-bottom: 2rem;
    }

    .login {
        font-family: 'Plus Jakarta Sans', sans-serif;
        font-weight: 400;
        text-align: center;
    }
    
</style>

<div class = "container-register">
    <div class = "register-header">
        <div class="warkop-kalisetail">
            Warkop Kalisetail
        </div>
        <div class="height-kalisetail">
            + 272 M
        </div>
    </div>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_table }}
        <div>
            <input class="register-button" type="submit" name="submit" value="Daftar"/>
        </div>
    </form>

    {% if messages %}
    <ul>
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    <div class="login">
        Already have an account yet?
        <a href="{% url 'main:login' %}">Login Now</a>
    </div>
    
</div>

{% endblock content %}